sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - texlive-fonts-recommended
    - lmodern
    - latex-xcolor
    - texlive-lang-italian
script: bash ./compile.sh
deploy:
  provider: releases
  api_key:
    secure: lWz3Kjh6mZhLp6k+snafDO/HpUeYOs+uZ0/Pi1GUX/vWHAre3nG+mMMdEXuk6d6Bwg8y/WB760yjyEXWaSxIViGZnR9oetw0wZiEF0PwIxUS9giEF6HE5GwhuOhNbQIIHsxpy21JR8zjzAhUpjCGjBQI31TP4qnFbJCy4Hi9A79lqtrt7E243iw8Evsefj96wbIE1QAcP90Kj/sS5KV1jwlQ6/z2+aG0pCy2Gp0GG6s89SOUo1b5MxFAaxnotbzDKchzuIUywm3lj6lM+DzKF3KVop482U/TQ+EwnhrUa2L6cZqSOZ9oZ5P3uovJ9gHKdMrOJpl0vVFdXfUTV0jgwgFsmGVxcXG6K8wUn6m+RPgCKF+WfmIw3hrN+xjhnXEp2ZLpiDkEE+CWbZmVJEPaGjnbyPNZ7exNzwpNh7CO1cTA8iLPAOEcWiP8llG2CNUO9Bkva4/jrtsscoLLyqIEJiBRJYpM8HeO4qfxJstSrCGTD1GqvakI66a/TheLfAK9/DRPfkVPjHEt6WfGbn01nuWiMsx+BpdHzpI5R0lbzr73qhAppiImP52ttX4mMvGPkKBTmkfmhEyBGgaxq7NoXXxnelC5ja5gecl8qr9NEScHzRV2UhnJSuYWMJ99M3E1BlXjS7z0xD1bGUH/1YBlypYF2mCU/CoF6mMa7m011C8=
  file: out/cv.pdf
  on:
    repo: mikeporterdev/LaTeX-CV
